// Post-`cap sync` patches for the generated (git-ignored) Android project.
//
// android/ is regenerated by Capacitor, so anything that must live in the native
// project has to be re-applied after every `npx cap add android`. This script
// makes those edits automatic and idempotent. It runs as part of `npm run sync`
// and is safe to run any time — it no-ops if android/ is missing.
//
// It does three things:
//   1. Injects the AdMob `APPLICATION_ID` meta-data (without it the app crashes
//      at startup once the Ads SDK is present — even with test ads).
//   2. Generates the launcher icon + the notification status-bar icon from the
//      app logo (icons/icon-512.png), so the app shows the real brand instead of
//      Capacitor's placeholder, and notifications use a proper white silhouette
//      instead of a gray square. Needs `sharp` (a devDependency).
//   3. Adds the FCM `default_notification_icon` meta-data so push notifications
//      pick up that same status-bar icon.
//
// ⚠️ Before publishing, replace ADMOB_APP_ID with your REAL AdMob App ID (and the
// real ad unit IDs in js/ads.js — see PUBLISHING.md "AdMob"). To change the logo,
// replace icons/icon-512.png (square, ideally 512px+) and re-run `npm run sync`.

import { readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

// Google's official TEST App ID — safe for development. App IDs use `~`,
// ad unit IDs use `/`; don't confuse the two.
const ADMOB_APP_ID = 'ca-app-pub-3940256099942544~3347511713';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const resDir = join(root, 'android', 'app', 'src', 'main', 'res');
const manifestPath = join(root, 'android', 'app', 'src', 'main', 'AndroidManifest.xml');
const logoPath = join(root, 'icons', 'icon-512.png');

const ADMOB_META = 'com.google.android.gms.ads.APPLICATION_ID';
const FCM_ICON_META = 'com.google.firebase.messaging.default_notification_icon';
const NOTIF_ICON = 'ic_stat_icon';

// Mipmap density buckets → launcher icon pixel size.
const DENSITIES = { mdpi: 48, hdpi: 72, xhdpi: 96, xxhdpi: 144, xxxhdpi: 192 };

async function patchManifest() {
  if (!existsSync(manifestPath)) {
    console.warn('! android/ not generated yet — run `npx cap add android` first, then `npm run sync`.');
    return;
  }
  let xml = await readFile(manifestPath, 'utf8');
  let changed = false;

  if (!xml.includes(ADMOB_META) && xml.includes('</application>')) {
    const tag =
      `    <meta-data\n` +
      `        android:name="${ADMOB_META}"\n` +
      `        android:value="${ADMOB_APP_ID}"/>\n`;
    xml = xml.replace('</application>', `${tag}    </application>`);
    changed = true;
    console.log(`✓ Added AdMob APPLICATION_ID (${ADMOB_APP_ID}) to AndroidManifest.xml`);
  }

  if (!xml.includes(FCM_ICON_META) && xml.includes('</application>')) {
    const tag =
      `    <meta-data\n` +
      `        android:name="${FCM_ICON_META}"\n` +
      `        android:resource="@drawable/${NOTIF_ICON}"/>\n`;
    xml = xml.replace('</application>', `${tag}    </application>`);
    changed = true;
    console.log(`✓ Added FCM default notification icon (@drawable/${NOTIF_ICON}) to AndroidManifest.xml`);
  }

  if (changed) await writeFile(manifestPath, xml);
  else console.log('✓ AndroidManifest.xml meta-data already present');
}

async function generateIcons() {
  if (!existsSync(resDir)) return; // android/ not generated; manifest step already warned
  if (!existsSync(logoPath)) {
    console.warn(`! ${logoPath} not found — skipping icon generation.`);
    return;
  }

  let sharp;
  try {
    sharp = (await import('sharp')).default;
  } catch {
    console.warn('! `sharp` not installed — skipping icon generation. Run `npm install` then `npm run sync`.');
    return;
  }

  // Launcher icons: legacy square + circular "round" variant, per density.
  for (const [bucket, sz] of Object.entries(DENSITIES)) {
    const dir = join(resDir, `mipmap-${bucket}`);
    await mkdir(dir, { recursive: true });
    await sharp(logoPath).resize(sz, sz, { fit: 'cover' }).png().toFile(join(dir, 'ic_launcher.png'));
    const circle = Buffer.from(
      `<svg width="${sz}" height="${sz}"><circle cx="${sz / 2}" cy="${sz / 2}" r="${sz / 2}" fill="#fff"/></svg>`
    );
    await sharp(logoPath)
      .resize(sz, sz, { fit: 'cover' })
      .composite([{ input: circle, blend: 'dest-in' }])
      .png()
      .toFile(join(dir, 'ic_launcher_round.png'));
  }

  // Capacitor ships adaptive-icon XML (mipmap-anydpi-v26) that points at its
  // placeholder foreground/background. Remove it so API 26+ falls back to the
  // legacy PNGs above instead of the placeholder.
  for (const name of ['ic_launcher.xml', 'ic_launcher_round.xml']) {
    await rm(join(resDir, 'mipmap-anydpi-v26', name), { force: true });
  }

  // Notification status-bar icon: white silhouette of the logo on transparency
  // (Android renders the alpha channel only; a full-color icon shows as a gray
  // square). One drawable is enough — Android scales it.
  const W = 96;
  const { data, info } = await sharp(logoPath)
    .resize(W, W, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  for (let i = 0; i < data.length; i += 4) {
    data[i] = 255; data[i + 1] = 255; data[i + 2] = 255; // keep alpha, force white
  }
  const drawableDir = join(resDir, 'drawable');
  await mkdir(drawableDir, { recursive: true });
  await sharp(data, { raw: { width: info.width, height: info.height, channels: 4 } })
    .png()
    .toFile(join(drawableDir, `${NOTIF_ICON}.png`));

  console.log('✓ Generated launcher + notification icons from icons/icon-512.png');
}

async function main() {
  await patchManifest();
  await generateIcons();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
