// Injects the AdMob APPLICATION_ID into the generated Android manifest.
//
// The Google Mobile Ads SDK requires a `com.google.android.gms.ads.APPLICATION_ID`
// meta-data entry in AndroidManifest.xml — WITHOUT it the app crashes natively at
// startup (even when serving test ads). Because android/ is generated by Capacitor
// and git-ignored, that edit would otherwise have to be re-applied by hand after
// every `npx cap add android`. This script makes it automatic and idempotent.
//
// Runs as part of `npm run sync`. Safe to run any time; it does nothing if the
// manifest is missing or already patched.
//
// ⚠️ Before publishing, replace ADMOB_APP_ID with your REAL AdMob App ID
// (and your real ad unit IDs in js/ads.js — see PUBLISHING.md "AdMob").

import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

// Google's official TEST App ID — safe for development. App IDs use `~`,
// ad unit IDs use `/`; don't confuse the two.
const ADMOB_APP_ID = 'ca-app-pub-3940256099942544~3347511713';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const manifestPath = join(root, 'android', 'app', 'src', 'main', 'AndroidManifest.xml');

const META_NAME = 'com.google.android.gms.ads.APPLICATION_ID';
const META_TAG =
  `    <meta-data\n` +
  `        android:name="${META_NAME}"\n` +
  `        android:value="${ADMOB_APP_ID}"/>\n`;

async function main() {
  if (!existsSync(manifestPath)) {
    console.warn('! android/ not generated yet — run `npx cap add android` first, then `npm run sync`.');
    return;
  }

  let xml = await readFile(manifestPath, 'utf8');

  if (xml.includes(META_NAME)) {
    console.log('✓ AdMob APPLICATION_ID already present in AndroidManifest.xml');
    return;
  }

  if (!xml.includes('</application>')) {
    console.warn('! Could not find </application> in AndroidManifest.xml — skipping AdMob patch.');
    return;
  }

  // Insert the meta-data just before the closing </application> tag.
  xml = xml.replace('</application>', `${META_TAG}    </application>`);
  await writeFile(manifestPath, xml);
  console.log(`✓ Added AdMob APPLICATION_ID (${ADMOB_APP_ID}) to AndroidManifest.xml`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
